# Generated by Django 4.1.3 on 2022-11-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(default='index.jpg', upload_to='profile'),
        ),
    ]
